"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import UserPanel from "@/utils/ReUse/UserPanel";
const inter = Inter({ subsets: ["latin"] });
import { usePathname } from "next/navigation";
import Navbar from "@/utils/LandingPage/Navbar";
// export const metadata = {
//   title: "Cloud Studio  -  Dashboard",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body className={inter.className }>{pathname.startsWith("/admin")?<UserPanel>{children}</UserPanel>:<><Navbar/>{children}</>}</body>
    </html>
  );
}
